partial commit for description and payload
citihub/probr pull request #180
Opened 2021-01-08 18:02 UTC by rparupell

2021-01-08 18:11 UTC, lcarrazana approved these changes

2021-01-08 18:46 UTC, eddie-knight requested changes

2021-01-08 18:46 UTC, eddie-knight commented on service_packs/kubernetes/general/general.go
> +	payload := struct{ podDashBoardName string }{name}
This will need to be capitalized to be printed in the JSON output, ex. `PodDashboardName`

I did pull & run the code just to double check before posting this 👍

2021-01-08 18:46 UTC, eddie-knight commented on service_packs/kubernetes/general/general.go
> +	payload := struct{ wildCardRolesCount int }{wildcardCount}
Payload values need to be public, unfortunately

2021-01-08 18:46 UTC, eddie-knight commented on service_packs/kubernetes/general/general.go
> +	payload := struct{ roleLevel string }{roleLevel}
Can you please make this public as well

2021-01-08 18:46 UTC, eddie-knight commented on service_packs/kubernetes/container_registry_access/container_registry_access.go
> +	payload := struct{ podState kubernetes.PodState }{s.podState}
Please make this public

2021-01-08 18:46 UTC, eddie-knight commented on service_packs/kubernetes/container_registry_access/container_registry_access.go
> +	payload := struct{ podState kubernetes.PodState }{s.podState}
Please make this public

2021-01-08 19:52 UTC, lcarrazana commented
Test coverage: https://img.shields.io/badge/coverage-70%25-green

2021-01-11 14:37 UTC, eddie-knight commented
#170

2021-01-11 14:43 UTC, eddie-knight commented on service_packs/kubernetes/container_registry_access/container_registry_access.go
> +	payload := struct{ PodState kubernetes.PodState }{s.podState}
Lets have the podState here in the payload, but not in the description (not two places)

2021-01-11 14:45 UTC, eddie-knight commented on service_packs/kubernetes/container_registry_access/container_registry_access.go
> +	payload := struct{ PodState kubernetes.PodState }{s.podState}
also, the description should contain information about the test (not the result).

2021-01-11 14:47 UTC, eddie-knight commented on service_packs/kubernetes/container_registry_access/container_registry_access.go
> +	description := fmt.Sprintf("Asserts pod creation result in scenario state is denied. Pod state is %v", s.podState)
lets leave this description the same as it was before :+1:

2021-01-11 14:52 UTC, eddie-knight commented on service_packs/kubernetes/iam/iam.go
> +	description := fmt.Sprintf("Attempting to get access from Pod is %s ", s.podState.PodName)
lets not duplicate PodName here

2021-01-11 14:52 UTC, eddie-knight commented on service_packs/kubernetes/iam/iam.go
> +	description := fmt.Sprintf("The Pod name deploying is %s ", s.podState.PodName)
Lets not repeat PodName here

2021-01-11 14:53 UTC, eddie-knight commented on service_packs/kubernetes/iam/iam.go
> +	description := fmt.Sprintf("Attempting to get access from Pod is %s ", s.podState.PodName)
Lets not repeat PodName here

2021-01-11 14:54 UTC, eddie-knight commented on service_packs/kubernetes/iam/iam.go
> +	description := "Cluster has managed identity componenet deployed"
*component

2021-01-11 14:54 UTC, eddie-knight commented on service_packs/kubernetes/iam/iam.go
> +	description := fmt.Sprintf("Executing command is %s,", arg1)
`Executing command %s`

2021-01-11 14:56 UTC, eddie-knight commented on service_packs/kubernetes/internet_access/internet_access.go
> +	description := fmt.Sprintf("The Pod %s deployed in the cluster", s.podState.PodName)
`Verifying a pod is deployed in the cluster`

2021-01-11 14:57 UTC, eddie-knight commented on service_packs/kubernetes/internet_access/internet_access.go
> +	description := fmt.Sprintf("Proces inside the pod established http connection with url %s,", url)
please put single quotes around values like this url value `url: '%s'`

2021-01-13 12:14 UTC, eddie-knight commented
When squashing+merging this PR, GitHub will default the commit message to use this PR name (not helpful for our commit history).

Changing the name won't actually resolve the issue- instead, please modify the commit message using the prompt that appears when this is going to be merged.

(I'll be copying this message to any similarly named PRs)

2021-01-14 17:23 UTC, closed without merging

2021-01-14 17:23 UTC, rparupell commented
This is closing because the same changes addressed in other PRS and they got merged already.