Summary unit test cases - partial commit
citihub/probr pull request #194
Opened 2021-01-19 13:39 UTC by rparupell

Since code changes are big, creating pull request with reasonable changes to review the code.

2021-01-19 14:21 UTC, eddie-knight requested changes

2021-01-19 14:21 UTC, eddie-knight commented on internal/summary/summary_test.go
> +	fakeSummaryState.Probes[fakeName].countResults()
Please pull this logic out to an independent function

2021-01-19 17:49 UTC, lcarrazana commented on internal/summary/summary_test.go
> +func createMockProbe(probename string) SummaryState {
Should the function name be: `createMockSummaryState` ?
Or maybe this: `createSummaryStateWithFakeProbes` ?

What are your thoughts?

2021-01-20 14:11 UTC, rparupell commented on internal/summary/summary_test.go
> +func createMockProbe(probename string) SummaryState {
i changed.committed pls review

2021-01-20 14:12 UTC, rparupell commented on internal/summary/summary_test.go
> +	fakeSummaryState.Probes[fakeName].countResults()
Done

2021-01-20 14:18 UTC, eddie-knight approved these changes

2021-01-20 14:18 UTC, lcarrazana approved these changes

2021-01-20 14:19 UTC, merged