New readme
citihub/probr pull request #195
Opened 2021-01-19 14:04 UTC by iantivey

2021-01-19 14:30 UTC, eddie-knight approved these changes

2021-01-19 14:52 UTC, eddie-knight requested changes

2021-01-19 14:52 UTC, eddie-knight commented on README.md
> +## Interactive Application Security Testing (IAST) for Cloud Infrastructure as Code
Looks like this title just _barely_ runs over onto two lines.

Since we aren't using the term IAST anywhere else in the document, defining it here doesn't serve a functional purpose. Can we drop `(IAST)` to get the title to fit on one line?

2021-01-19 14:52 UTC, eddie-knight commented on README.md
> +An example Vars file is available at [probr/examples/config.yml](./probr/examples/config.yml).
This link doesn't work as it should when viewed on the feature branch... I suspect this should be `./examples/config.yml`

2021-01-19 14:52 UTC, eddie-knight commented on README.md
> +**IMPORTANT:** Try to avoid putting secrets into your config file.  If you do need to have then in the config file, remember not to commit to git and encrypt your config file.
1. `If you do need to have then...` should be `them` or `secrets`.
1. Encrypting a file with something like _Ansible Vault_ allows the file to be safely committed to git... So it would be more accurate to say `...remember to encrypt your config file, or avoid committing it to your git repository.`

2021-01-19 18:09 UTC, iantivey commented on README.md
> +## Interactive Application Security Testing (IAST) for Cloud Infrastructure as Code
I kept IAST in the title for the SEO.

2021-01-19 18:10 UTC, iantivey commented on README.md
> +**IMPORTANT:** Try to avoid putting secrets into your config file.  If you do need to have then in the config file, remember not to commit to git and encrypt your config file.
Removed

2021-01-19 19:14 UTC, eddie-knight approved these changes

2021-01-20 10:15 UTC, iantivey commented on examples/config.yml
> +    TenantID: "6d1664ba-5a5c-11eb-ae93-0242ac130002"
If we can merge this first, then that PR will overwrite this.

2021-01-20 13:29 UTC, paulm-jones approved these changes

2021-01-20 14:11 UTC, merged

2021-01-22 17:55 UTC, lcarrazana commented on examples/config.yml
> +    TenantID: "6d1664ba-5a5c-11eb-ae93-0242ac130002"
FYI: I cancelled my PR after I saw this was coming, so this version is the current one.