[FEATURE-58] New tagging strategy
citihub/probr pull request #63
Opened 2020-11-04 17:52 UTC by iantivey

2020-11-04 21:59 UTC, paulm-jones commented
Just getting back in the game.

Can we squash commits for merges like this? Helps keep the trunk clean.

2020-11-06 12:23 UTC, eddie-knight commented
@paulm-jones 
We've been defaulting to squash&merge for all PRs, so the commit history here shouldn't pose a problem for the main git history

2020-11-06 12:25 UTC, eddie-knight requested changes
@simonwoolhouse can you please investigate whether a functional change to support these proposed new service pack names in our exclusion logic?

2020-11-06 14:28 UTC, paulm-jones commented
@eddie-knight - incoming PR into @iantivey's adding a README covering tag usage & also fixing some typos I spotted whilst looking at tags.

Once Ian merges it'll show up here.

2020-11-06 15:55 UTC, eddie-knight commented
@iantivey I have concerns about the language used here for the tags. Apologies for not bringing this up on the call earlier, I only just did some more investigating on this.

First and foremost, "family" seems to mean very different things between CIS and NIST, which brings me to an opinion that using that term in our tags would be unclear at best.

Second, I believe we would benefit from first creating a tree-style heirarchy to ensure that our usage is clear, concise, and consistent.

2020-11-06 15:57 UTC, eddie-knight commented on Dockerfile
> +ENTRYPOINT ["./entrypoint.sh"]
This change appears to be separate from the overall theme of the PR... please isolate this change to an independent PR so that we can have that review independently from the discussion surrounding tags.

2020-11-06 16:51 UTC, paulm-jones commented
> @iantivey I have concerns about the language used here for the tags. Apologies for not bringing this up on the call earlier, I only just did some more investigating on this.
> 
> First and foremost, "family" seems to mean very different things between CIS and NIST, which brings me to an opinion that using that term in our tags would be unclear at best.
> 
> Second, I believe we would benefit from first creating a tree-style heirarchy to ensure that our usage is clear, concise, and consistent.

Can you explain what you mean, isn't that what this change introduces?

2020-11-06 16:55 UTC, paulm-jones commented
> First and foremost, "family" seems to mean very different things between CIS and NIST, which brings me to an opinion that using that term in our tags would be unclear at best.

I don't think I know what you mean here either. Might not CIS and NIST both cover, for example, data encryption or RBAC?

2020-11-11 19:18 UTC, eddie-knight commented
> Might not CIS and NIST both cover, for example, data encryption or RBAC?
The point I wanted to address is that "family" means something different depending on where you look.

CIS has have [product families](https://www.cisecurity.org/cis-benchmarks/) and their CSC version 6 (while outdated) clutters the search a bit by using the term "family" to categorize the various controls.

Different from the CIS product families, but similar to the CSCv6 families, NIST has [access control families](https://nvd.nist.gov/800-53/Rev4/family/Access%20Control). The previous link is unique to Rev4, but (Rev5)[https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-53r5-draft.pdf] still uses the same term.

> isn't that what this change introduces?

Just based on my first look, it didn't seem very tree-like, but I'll spend some more time on it. I'll put together a nested bullet point list of the terms and will bring this up again if I have any more concerns about it.

2020-11-11 19:44 UTC, eddie-knight commented on probes/README.md
> +| `@control/family` | Used as a general categorisation for Probes that cover specific, cloud agnostic functional areas | `container_registry_access`, `general`, `iam`, `pod_security_policy`, `network
For reference...

- control
  - type
    - detective
    - preventative
  - family
    - container_registry_access
    - general
    - iam
    - pod_security_policy
    - network
- csp
  - all
  - aws
  - azure
  - gcp
  - openshift
- service
  - kubernetes
- standard
  - cis
  - citihub

Side notes:
- In this PR, it seems that `@control/type` and `@control/family` aren't related, so they probably don't need to have the shared parent of `control`
- It seems the two aforementioned tags and are typically used together with a probe having a "family" and all of it's scenarios being tagged with the same "type", so in the present state there is always one type and one scenario per probe
- Have we already made our own list of standards similar to CIS? Should we link to that from the main README, if we're going to be using it? 
- Doesn't need to be now, but we might as well create a section in the README describing any standards our probes comply with
- Regarding `csp/all` ...do we foresee having any controls that will _not_ work on one or all of the cloud providers? That's the only reason I can see us needing this tag.

2020-11-12 06:50 UTC, paulm-jones commented on probes/README.md
> +| `@control/family` | Used as a general categorisation for Probes that cover specific, cloud agnostic functional areas | `container_registry_access`, `general`, `iam`, `pod_security_policy`, `network
Taken in order:

- type and family: I think that's fair, we could just have `@type` and `@family`
- In the other repo we have family = object storage and type = both preventative (e.g. Azure Policy) and detective (e.g. AWS Config)
- I think ultimately we might, yes, but we haven't made the decision to open source it yet... in time & if we can get it into a good enough state
- In addition to the `@CIS-a.b.c` tags you mean?
- Yes I think it's feasible if for example we're testing a service that doesn't really have a comparator in another cloud. AWS ('cause it has millions of services) will have plenty, theoretically.

2020-11-12 06:53 UTC, paulm-jones commented
> CIS has product families and their CSC version 6 (while outdated) clutters the search a bit by using the term "family" to categorize the various controls.

Different from the CIS product families, but similar to the CSCv6 families, NIST has access control families. That link is unique to Rev4, but Rev5 still uses the same term.

We could go with `category` instead, or suggest a different word?

> Just based on my first look, it didn't seem very tree-like

We just had `control/type` and `/family` but seem to have agreed to flatten it :-)

2020-11-12 12:04 UTC, eddie-knight commented on probes/README.md
> +| `@control/family` | Used as a general categorisation for Probes that cover specific, cloud agnostic functional areas | `container_registry_access`, `general`, `iam`, `pod_security_policy`, `network
1. `@type` and `@family` sounds good to me
1. That response does clear up the confusion
1. In that case, could we drop the reference to `@standards/citihub` until it's relevant?
1. Yeah, but also including CIS. I'll revisit this later.
1. The alibaba comment made me chuckle. Good point.

2020-11-12 12:07 UTC, eddie-knight commented
That's a good suggestion @paulm-jones 

It feels like a small issue to get caught up on, but I would prefer the more generic term `category` over `family` just to help keep people like me from getting too cerebral about the meaning.

2020-12-03 14:36 UTC, closed without merging