Feature/unflatten config vars
citihub/probr pull request #77
Opened 2020-11-13 15:18 UTC by simonwoolhouse

This change currently breaks probr due to a YAML parsing problem for embedded structures.

2020-11-16 15:32 UTC, eddie-knight requested changes

2020-11-16 15:32 UTC, eddie-knight commented on README.md
> +Command line options can be obtained via `./probr --help`
Regarding the edits on lines `3-21`, can you save these changes for a separate PR? 

It'd help simplify the review process if this PR only has the config var changes and any docs changes related to the config vars. I like these suggestions, so don't trash them... but it'd be nice to isolate any changes to the PR topic so we can have more targeted discussion and review.

2020-11-16 15:32 UTC, eddie-knight commented on README.md
> +|Kubernetes.KubeConfig|Path to kubernetes config|yes|yes|KUBE_CONFIG|N/A|
the default value here is `~/.kube/config`

2020-11-16 15:32 UTC, eddie-knight commented on README.md
> +|Tags|Feature tag inclusions and exclusions|yes|yes|PROBR_TAGS|""|
Since we aren't including the string-quotes on other variables, I suspect it would be more "clear" to just leave the default cell empty if the default is an empty string (just remove the `""`)

2020-11-16 15:32 UTC, eddie-knight commented on README.md
> +|OutputDir|Path to output dir if applicable|yes|yes|PROBR_CUCUMBER_DIR|cucumber_output|
Spitballing here, but it seems like we should probably correct the name `OutputDir` to `CucumberDir` everywhere that it's being used

2020-11-16 15:32 UTC, eddie-knight commented on README.md
> +|OutputType|Determines output to file (IO) or terminal (INMEM)|yes|yes|PROBR_OUTPUT_TYPE|INMEM|
The code isn't super clear in this area, apologies for that... For this description let's say:
`"IO" will write to file, as is needed for CLI usage. "INMEM" should be used in non-CLI cases, where values should be returned in-memory instead.`

Also, I double checked and the default value here is `IO`

2020-11-16 15:32 UTC, eddie-knight commented on README.md
> +|Silent|Disable visual runtime indicator|yes|no|N/A|true|
FYI: `--silent` defaults to false unless the flag is passed... though this is understandably confusing because once the flag _is_ passed, it defaults to true (allowing `--silent` to be used instead of requiring `--silent=true`)

2020-11-16 15:57 UTC, simonwoolhouse commented
When I update OutputDir to CucumberDir, should I update OutputType to Cucumber_Type? 
Sounds a bit odd - 'long, green and slim', or 'short, green and thick' perhaps :)

2020-11-16 16:00 UTC, eddie-knight commented on README.md
> +|OutputDir|Path to output dir if applicable|yes|yes|PROBR_CUCUMBER_DIR|cucumber_output|
> When I update OutputDir to CucumberDir, should I update OutputType to Cucumber_Type?
> Sounds a bit odd - 'long, green and slim', or 'short, green and thick' perhaps :)
@simonwoolhouse 

No, the `OutputType` is a bit different... Earlier today we discussed making functional changes to that logic, but it's not inherently related to the cucumber output so it'll be beyond the scope of this PR.

2020-11-17 11:50 UTC, eddie-knight approved these changes
Pulled and ran against the tivey cluster, works as expected. Thanks for knocking this out!

2020-11-17 11:51 UTC, merged